### ISSUE TITLE
hypercorn v0.16.0 ?

### ISSUE THREAD

**Issue by davidbrochart** [conda-forge/hypercorn-feedstock#43]
### Comment:

I see [hypercorn v0.16.0 on PyPI](https://pypi.org/project/Hypercorn/0.16.0/), but the current feedstock is 0.14.3.
Do you know why?

**Comment by bollwyvl** [comment]
`hypercorn 0.17.3` is now available, so we can probably close this out.

https://anaconda.org/conda-forge/hypercorn/files?version=0.17.3

If some downstream needs that _specific_ historical version, please feel free to re-open this issue or start a new one.
